### ISSUE TITLE
Bajo rendimiento - Issue

### ISSUE THREAD

**Issue by PabloCerrada** [Proyectos1-FDI-UCM/c2022-Grupo09#15]
### Descripción

El juego funciona con muy bajo rendimiento. El origen podrían ser las frutas (seguramente fallo al programar).
Lo que debería pasar sería que el juego funcionase con buen rendimiento.

### Pasos 

Simplemente juega la prueba de power-ups y comprobarás el bajo rendimiento.

### Captura de pantalla o vídeo

[![Texto alternativo](https://img.youtube.com/vi/LuQgN3JqQT4/0.jpg)](https://youtu.be/LuQgN3JqQT4)

**Comment by DDiegoP** [comment]
Problema de la escena de test de power-ups
