### ISSUE TITLE
Balas mal posicionadas - Issue

### ISSUE THREAD

**Issue by PabloCerrada** [Proyectos1-FDI-UCM/c2022-Grupo09#17]
### Descripción

Los enemigos situados en el techo (las torretas) disparan las balas desde una posición no deseada.
Lo que debería pasar sería que la bala saliese de la punta del cañon de la torreta.

### Pasos 

1. Llegar a la segunda fase
2. Fijarse en las balas que salen de las torretas

### Vídeo

[![Texto alternativo](https://img.youtube.com/vi/U05ZT49cui0/0.jpg)](https://youtu.be/U05ZT49cui0)

**Comment by DDiegoP** [comment]
Parece que se trata de un fallo tan solo de la escena de pruebas
