### ISSUE TITLE
Colisión de enemigos contra la pared que se abre y cierra

### ISSUE THREAD

**Issue by AgusCDT** [Proyectos1-FDI-UCM/c2022-Grupo09#21]
### Descripción
En la prueba de combate, cuando la pared está cerrada los enemigos al chocar con ella no cambian de dirección quedándose pillados con la pared.

### Pasos
-	Ir a la prueba de combate
-	Mantener una puerta cerrada
-	Observar como los enemigos se quedan pillados

### Captura de pantalla

![image](https://user-images.githubusercontent.com/100000318/165734783-658b3bd8-4c8e-4b66-ba07-c5a38f84f27e.png)

**Comment by DDiegoP** [comment]
Issue duplicado
