### ISSUE TITLE
Moonwalk

### ISSUE THREAD

**Issue by AgusCDT** [Proyectos1-FDI-UCM/c2022-Grupo09#24]
### Descripción
En la prueba de Power Ups, el player hace moonwalk de vez en cuando.

### Pasos
-	Ir a la prueba de Power Ups
-	Ir de un lado a otro como en el vídeo

### Vídeo
[![Texto alternativo](https://img.youtube.com/vi/RD_y0YHciUw/0.jpg)](https://youtu.be/RD_y0YHciUw)

**Comment by DDiegoP** [comment]
Es un problema de la escena de pruebas, debido al volumen de enemigos cargados hay problemas de rendimiento que causan que las animaciones no cambien correctamente
