### ISSUE TITLE
Error con el kiwi (2)

### ISSUE THREAD

**Issue by AgusCDT** [Proyectos1-FDI-UCM/c2022-Grupo09#25]
En adición a #8 
### Descripción
En la prueba de Power Ups, el kiwi no ralentiza el tiempo de los enemigos correctamente. Se espera que los enemigos vayan más lentos. Su movimiento funciona correctamente, pero tanto la cadencia de disparo como las balas no van más lentas.

### Pasos
-	Ir a la prueba de Power Ups
-	Coger el kiwi 
-	Comprobar como los enemigos voladores se mueven más lentos pero no las balas.

**Comment by DDiegoP** [comment]
Error duplicado
