### ISSUE TITLE
Bug en el nivel 2

### ISSUE THREAD

**Issue by AgusCDT** [Proyectos1-FDI-UCM/c2022-Grupo09#27]
### Descripción
En la exploración del juego, hay un bug en el nivel 2 el cual no te deja moverte además de que, aunque mates al enemigo, éste revive.

### Pasos
-	Ir al nivel 2.
-	Dirigirse nada más empezar, arriba a la izquierda.
-	Comprobar el fallo como en el vídeo.

### Vídeo
[![Texto alternativo](https://img.youtube.com/vi/w5_zVhA9gcE/0.jpg)](https://youtu.be/w5_zVhA9gcE)

**Comment by DDiegoP** [comment]
No es replicable con la información proporcionada
