### ISSUE TITLE
Engranajes

### ISSUE THREAD

**Issue by AgusCDT** [Proyectos1-FDI-UCM/c2022-Grupo09#28]
### Descripción
Al devolver los engranajes en la batalla final. A veces los destruyes y otras los devuelve hacia izquierda o derecha.

### Pasos
-	Ir a la batalla final.
-	Devolver engranajes hasta encontrar el error.

**Comment by DDiegoP** [comment]
Los engranajes se destruyen al devolvérselos al jefe, si es a lo que te refieres
