### ISSUE TITLE
Animación enemigo muerte

### ISSUE THREAD

**Issue by Cao33** [Proyectos1-FDI-UCM/c2022-Grupo09#31]
### Descripcion

Al acceder a la sala 3 y no activar la palanca se ve que los enemigos están fijos y o tienen movimiento hasta que se le da a la palanca

### Pasos
1.Prueba de combate
2. Llegar a la sala 3 sin activar la palanca de esa sala

[![Video](https://img.youtube.com/vi/OTmsTkxX6xE/0.jpg)](https://youtu.be/OTmsTkxX6xE)

**Comment by DDiegoP** [comment]
El título del issue, la descripción y el video adjuntado no corresponden entre sí

**Comment by DDiegoP** [comment]
Los bugs a los que hace referencia el título, la descripción o el video adjuntado ya son issues reportados
