### ISSUE TITLE
Salto en pared impulso extraño

### ISSUE THREAD

**Issue by Cao33** [Proyectos1-FDI-UCM/c2022-Grupo09#34]
###Descripcion

Si se salta de un salto sobre una pared hay veces que te desplaza hacia arriba una distancia muy larga sin necesidad de doble salto ni impulso

### Pasos
1. Ir a prueba de combate
2. Saltar sobre una pared

[![Video](https://img.youtube.com/vi/qAXASraHV2I/0.jpg)](https://youtu.be/qAXASraHV2I)

**Comment by luisja30** [comment]
Oye Cao33, no nos deja ver los videos porque los has puesto en privado. Debes ponerlo en oculto. Un saludo.
